spring.application.name=ebank-bot
#spring.config.import=file:env.properties[.properties]
spring.ai.openai.chat.model=gpt-4o
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
server.port=8058
spring.ai.mcp.client.streamable-http.connections.customers.url=http://localhost:8056/mcp
spring.ai.mcp.client.streamable-http.connections.ebank.url=http://localhost:8057/mcp
eureka.instance.prefer-ip-address=true
discord.token=${DISCORD_TOKEN}
spring.ai.openai.api-key=${OPEN_AI_KEY}